# markdown: kramdown

# For related posts
# lsi: true
# highlighter: pygments

permalink: pretty
paginate: 5
paginate_path: "news/page:num"

safe: true

title: The Poisot Lab
subtitle: Numerical and Computational Ecology
author: Timothée Poisot
production_url: http://poisotlab.io

featured_papers:
    - delm17aen
    - pois16dup
    - pois16spn
    - pois15swe
    - pois16sdc
    - pois17hpt
    - pois17dss

sass:
    style: compressed
