# markdown: kramdown

# For related posts
# lsi: true
# highlighter: pygments

permalink: pretty
paginate: 5
paginate_path: "news/page:num"

safe: true

title: Andrew Tredennick
subtitle: Quantitative Ecology
author: Andrew Tredennick
production_url: http://atredennick.github.io

featured_papers:
    - Deitze2018
    - Tredennick2017b

sass:
    style: compressed
