# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            andrew tredennick
tagline:          'plant population and community ecologist'
description:      'Population and community ecologist at Utah State University <a href="https://twitter.com/atredennick" target="_blank">@atredennick</a>' 
url:              http://atredennick.github.io

author:
  name:           'Andrew Tredennick'
  url:            https://twitter.com/atredennick

# paginate:         5

github:
  repo:           https://github.com/atredennick/atredennick.github.io
